language: c
sudo: true
os:
  - linux
  - osx

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - libuv-dev
      - cmake
      - cmake-data

before_install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]];
    then
    brew update;
    brew outdated cmake || brew upgrade cmake;
    else
    sudo apt-get install libuv-dev
    fi
  - export PATH=$HOME/.local/bin:$PATH
  - pip install cpp-coveralls --user `whoami`

script:
- ./build.sh all
